const schools_of_magic = ["abjuration", "conjuration", "divination", "enchantment", "evocation", "illusion", "necromancy", "transmutation"]
// reminder the array starts at 0

export const CANTRIPS =
[
    {name: "Guidance", school: schools_of_magic[2], castingTime: "1 action", range: "touch", components: ["V", "S"], material: null, concentration: true, duration: "1 minute", usableBy:["Artificer", "Cleric", "Druid"],
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends."},
    {name: "Light", school: schools_of_magic[3], castingTime: "1 action", range: "touch", components: ["V", "M"], material: "a firefly or phosphorescent moss", concentration: false, duration: "1 hour", usableBy: ["Artificer", "Bard", "Cleric", "Sorceror", "Wizard"],
        description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action.\nIf you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell."},
    {name: "Acid Splash", school:schools_of_magic[1], castingTime: "1 action", range: "60 feet", components: ["V", "S"], material: null, concentration: false, duration: "instantaneous", usableBy:["Artificer", "Sorceror", "Wizard"],
        description: "You hurl a bubble of acid. Choose one creature you can see within range, or choose two creatures you can see within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage."},
    {name: "Mage Hand", school: schools_of_magic[1], castingTime: "1 action", range: "30 feet", components: ["V", "S"], material: null, concentration: false, duration: "1 minute", usableBy: ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
        description: "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.\nYou can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can't attack, activate magic items, or carry more than 10 pounds with the hand."},
    {name: "Fire Bolt", school: schools_of_magic[4], castingTime: "1 action", range: "120 feet", components: ["V", "S"], material: null, concentration: false, duration: "instantaneous", usableBy: ["Artificer", "Sorcerer", "Wizard"],
        description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried."},
    {name: "Thaumaturgy", school: schools_of_magic[5], castingTime: "1 action", range: "30 feet", components: ["V"], material: null, concentration: false, duration: "up to 1 minute", usableBy: ["Cleric"],
        description: "You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range:\n• Your voice booms up to three times as loud as normal for 1 minute.\n• You cause flames to flicker, brighten, dim, or change color for 1 minute.\n• You cause harmless tremors in the ground for 1 minute.\n• You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers.\n• You instantaneously cause an unlocked door or window to fly open or slam shut.\n• You alter the appearance of your eyes for 1 minute.\nIf you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action."},
    {name: "Mending", school: schools_of_magic[0], castingTime: "1 minute", range: "touch", components: ["V", "S", "M"], material: "two lodestones", concentration: false, duration: "instantaneous", usableBy: ["Artificer", "Bard", "Cleric", "Druid", "Sorcerer", "Wizard"],
            description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage.\nThis spell can physically repair a magic item or construct, but the spell can't restore magic to such an object."}

    //Incomplete
]
export const FIRST_LEVEL_SPELLS =
[
    {name: "Absorb Elements", school: schools_of_magic[0], castingTime: "1 reaction, when you take acid, cold, fire, lightning, or thunder damage", range: "self", components: ["S"], material: null, concentration: false, duration: "1 round", usableBy:["Artificer", "Druid", "Ranger", "Sorcerer", "Wizard"],
        description: "The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends."},

    {name: "Burning Hands", school: schools_of_magic[2], castingTime: "1 action", range: "Self (15-foot cone)", components: ["V", "S"], material: null, concentration: false, duration: "Instantaneous", usableBy:["Sorcerer", "Wizard"],
        description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren't being worn or carried."},

    {name: "Cure Wounds", school: schools_of_magic[1], castingTime: "1 action", range: "Touch", components: ["V", "S"], material: null, concentration: false, duration: "Instantaneous", usableBy:["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
        description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs."},

    {name: "Detect Magic", school: schools_of_magic[2], castingTime: "1 action", range: "Self", components: ["V", "S"], material: null, concentration: true, duration: "Up to 10 minutes", usableBy:["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
        description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt."},
        
    {name: "Feather Fall", school: schools_of_magic[4], castingTime: "1 reaction, which you take when you or a creature within 60 feet of you falls", range: "60 feet", components: ["V", "M"], material: "a small feather or piece of down", concentration: false, duration: "1 minute", usableBy:["Bard", "Sorcerer", "Wizard"],
        description: "Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet, and the spell ends for that creature."}
];
